import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NextJS Todolist + Supabase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Todo App!</h1>
        <Link href={"/todos"}>
          <a>Go to todo page</a>
        </Link>
      </main>
    </div>
  );
};

export default Home;
